[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

[font]
normal.family = "FiraCode Nerd Font Mono"
# normal.family = "MonaspiceNe Nerd Font"

size = 14

offset.x = 1
offset.y = 5

[general]
import = [
  "~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"
]
